# -*- coding: utf-8 -*-
"""Copy of diabeties predi

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11i97BGE43pHLX2JJ2poxmDKy0Mdx1i7_
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from google.colab import files 
uploaded=files.upload()

data=pd.read_csv('diabetes.csv')

print(data)

data.info

data.describe()

data.groupby('Outcome').mean()

sns.heatmap(data)

X=data.drop('Outcome',axis=1)
Y=data['Outcome']
print(X)
print(Y)

scaler=StandardScaler()
finaldata=scaler.fit_transform(data)

scaler=StandardScaler()
X=scaler.fit_transform(X)
Y=data['Outcome']

print(X)
print(Y)

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

from sklearn import svm
classifier=svm.SVC(kernel='linear')
classifier.fit(X_train,Y_train)

X_train_predict=classifier.predict(X_train)
accuracy=accuracy_score(X_train_predict,Y_train)

print(accuracy)

X_test_predict=classifier.predict(X_test)
accuracy=accuracy_score(X_test_predict,Y_test)
print(accuracy)

input_data=(3,78,50,32,88,31,0.2,26)
array=np.asarray(input_data)

reshaped=array.reshape(1,-1)

finaldata=scaler.transform(reshaped)

prediction=classifier.predict(finaldata)

print(prediction)

